# SPDX-FileCopyrightText: 2026 Avogadro Project
# SPDX-License-Identifier: BSD 3-Clause
# ******************************************************************************
# This source file is part of the Avogadro project.
#
# This source code is released under the New BSD License, (the "License").
# ******************************************************************************
"""Input generation for the UK variant of GAMESS."""


def generateInputFile(input_json: dict) -> tuple[str, list[str]]:
    # Collect warning strings as we go
    warnings = []

    # Extract options:
    opts = input_json["options"]
    title = opts["Title"]
    calculate = opts["Calculation Type"]
    theory = opts["Theory"]
    basis = opts["Basis"]
    charge = opts["Charge"]
    multiplicity = opts["Multiplicity"]
    directScf = opts["Direct SCF Mode"]

    # Convert to code-specific strings
    calcStr = ""
    if calculate == "Single Point":
        calcStr = "scf"
    elif calculate == "Equilibrium Geometry":
        calcStr = "optxyz"  # TODO If we add zmatrix, this will need updating.
    elif calculate == "Frequencies":
        calcStr = "hessian"
    elif calculate == "Transition State":
        calcStr = "saddle"
    else:
        warnings.append(f"Unhandled calculation type: {calculate}")

    theoryStr = ""
    if theory in ["RHF", "MP2"]:
        theoryStr = "scftype "
        if directScf:
            theoryStr += "direct "
        theoryStr += theory.lower()
    elif theory in ["B3LYP", "BLYP", "SVWN", "B97", "HCTH", "FT97"]:
        if directScf:
            theoryStr += "scftype direct\n"
        theoryStr += f"dft {theory.lower()}"
    else:
        warnings.append(f"Unhandled theory type: {theory}")

    basisStr = ""
    if basis == "STO-3G":
        basisStr = "sto3g"
    elif basis == "6-31G(d)":
        basisStr = "6-31G*"
    elif basis in ["3-21G", "6-31G", "cc-pVDZ", "cc-pVTZ"]:
        basisStr = basis
    else:
        warnings.append(f"Unhandled basis type: {basis}")

    generated_input = ""

    # Copied from 1.x extension. Seems useful.
    generated_input += "# This file was generated by Avogadro\n"
    generated_input += "# For more GAMESS-UK input options consult the manual at:\n"
    generated_input += "# http://www.cfs.dl.ac.uk/docs/index.shtml\n\n"

    generated_input += f"title\n{title}\n\n"

    if calculate in ["Equilibrium Geometry", "Transition State"]:
        generated_input += "# Ensure orbital vectors printed after optimization:\n"
        generated_input += "iprint vectors\n\n"

    generated_input += f"mult {multiplicity:d}\ncharge {charge:d}\n\n"

    generated_input += "geometry angstrom"
    if calculate == "Transition State":
        generated_input += " all"
    generated_input += "\n"

    generated_input += "$$coords:_xyzZS$$\nend\n\n"

    generated_input += f"basis {basisStr}\n\n"

    generated_input += f"runtype {calcStr}\n"
    generated_input += f"{theoryStr}\n\n"

    generated_input += "enter\n"

    return generated_input, warnings


def generateInput(input_json: dict, debug: bool) -> dict:  # noqa: FBT001

    generated_input, warnings = generateInputFile(input_json)

    filename = input_json["options"]["Filename Base"] + ".gukin"

    result = {
        "files": [
            {"filename": filename, "contents": generated_input},
        ],
        "mainFile": filename,
    }

    if warnings:
        result["warnings"] = warnings

    return result
