name: lint_python

on: [pull_request, push]

jobs:
  lint_python:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/setup-uv@v10.0.1
        with:
          version: "0.12.5"
          python-version: 3.11
      - run: uv sync --group dev
      - run: uvx ruff format --check
      - run: uvx codespell **.py
      - run: uvx ruff check
